// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fGF8Dahj979fdVuEqA-bnWwksVFVvys',
    appId: '1:107638942496:web:465b3c4da3f68cc41b0545',
    messagingSenderId: '107638942496',
    projectId: 'kamsa-data',
    authDomain: 'kamsa-data.firebaseapp.com',
    storageBucket: 'kamsa-data.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF6Yrk2ZzN68w2oPaQD6IP2GM_yb8JFr0',
    appId: '1:107638942496:android:4930f03dae705de71b0545',
    messagingSenderId: '107638942496',
    projectId: 'kamsa-data',
    storageBucket: 'kamsa-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjKt4nJdV75eQc6tsEbBe2eiXGM8w31p4',
    appId: '1:107638942496:ios:cb567f4e7b7ea4851b0545',
    messagingSenderId: '107638942496',
    projectId: 'kamsa-data',
    storageBucket: 'kamsa-data.firebasestorage.app',
    iosBundleId: 'com.kamsastore.kamsaStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjKt4nJdV75eQc6tsEbBe2eiXGM8w31p4',
    appId: '1:107638942496:ios:cb567f4e7b7ea4851b0545',
    messagingSenderId: '107638942496',
    projectId: 'kamsa-data',
    storageBucket: 'kamsa-data.firebasestorage.app',
    iosBundleId: 'com.kamsastore.kamsaStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fGF8Dahj979fdVuEqA-bnWwksVFVvys',
    appId: '1:107638942496:web:7d60ab86c7d5f5261b0545',
    messagingSenderId: '107638942496',
    projectId: 'kamsa-data',
    authDomain: 'kamsa-data.firebaseapp.com',
    storageBucket: 'kamsa-data.firebasestorage.app',
  );
}
